export default {
  "zh-CN": {
    "transMsg": [
      "预览图片失败",
      "评论成功",
      "提交中…",
      "加载中…",
      "领取成功",
      "保存成功",
      "添加成功",
      "申请售后成功",
      "没有更多售后了",
      "没有更多用户收藏了",
      "删除成功",
      "感谢您的反馈！",
      "没有更多用户足迹了",
      "绑定失败：请先登录",
      "绑定手机号码成功",
      "没有更多订单了",
      "取消订单成功",
      "删除订单成功",
      "确认收货成功！",
      "账户登录失败",
      "微信登录失败",
      "请选择收货地址",
      "只能上传五张图片",
      "请填写评论",
      "请选择完整规格",
      "没有库存",
      "支付失败",
      "请输入姓名",
      "请输入手机号码",
      "请输入省市区",
      "请输入详细地址",
      "手机号不正确",
      "请选择退款类型",
      "请输入退款原因",
      "请输入兑换码",
      "请选择反馈类型",
      "请输入反馈内容",
      "请输入手机号码",
      "更新提示",
      "错误信息",
      "发送成功",
      "密码重置失败",
      "错误",
      "警告",
      "存图成功",
      "新版本已经准备好，是否重启应用？",
      "请输入用户名和密码",
      "手机号不能为空",
      "手机号输入不正确",
      "验证码已发送",
      "用户名和密码不得少于6位",
      "确认密码不一致",
      "手机号和验证码不能为空",
      "手机号输入不正确",
      "注册失败",
      "验证码已发送",
      "用户名和密码不得少于3位",
      "上传失败",
      "不授权无法保存",
      "图片成功保存到相册了，可以分享到朋友圈了",
      "确定要删除地址？",
      "确定删除吗？",
      "要删除所选足迹？",
      "退出登录？",
      "确定要取消此订单？",
      "确定要删除此订单？",
      "确认收货？",
      "确定",
      "取消"
    ]
  },
  "en": {
    "transMsg": [
      "Descarga sin éxito",
      "Comentario subido",
      "Enviando...",
      "Descargando...",
      "Conseguido",
      "Guardado",
      "Agregado",
      "Solicitud enviada",
      "没有更多售后了",
      "No hay más favoritos",
      "Eliminado",
      "Gracias por tu opinión",
      "No hay más huellas",
      "Viculación fallada: inicia sesión",
      "Número celular vinculado",
      "No hay más orden",
      "Orden anulada",
      "Orden eliminada",
      "Recepción confirmada",
      "Inicio de sesión fallado con cuenta",
      "Inicio de sesión fallado con WeChat",
      "Elige dirección de entrega",
      "Maxímo 5 fotos",
      "Por favor escribe tu opinión ",
      "Por favor elige especificaciones completas",
      "Sin stock",
      "Transacción fallida",
      "Por favor ingresa tu nombre",
      "Por favor ingresa numero celular",
      "Por favor ingresa región, ciudad y comuna",
      "Por favor ingresa dirección completa",
      "Numero celular incorrecto",
      "Por favor elige tipo de reembolso",
      "Por favor ingresa razón de reembolso",
      "Por favor ingresa número de código",
      "Por favor elige tipo de comentario",
      "Por favor ingresa comentario",
      "Por favor ingresa número celular",
      "Aviso de actualización",
      "Información incorrecta",
      "Enviado",
      "Error al restablecer contraseña",
      "Error ",
      "Advertencia",
      "Foto guardada",
      "La nueva versión está lista.Querías reinicar la aplicación ?",
      "Por favor ingresa nombre usuario y contraseña",
      "Espacio de número celular es obligatorio",
      "Número celular incorrecto",
      "Código de verificación enviado",
      "Mínimo 6 números o letras para nombre usuario y contraseña",
      "Contraseñas diferente",
      "Espacio de número celular y código de verificación es obligatorio",
      "Número celular incorrecto",
      "Registración fallida",
      "Código de verificación enviado",
      "Mínimo 3 números o letras para nombre usuario y contraseña",
      "Carga sin éxito",
      "No se puede guardar sin autorización",
      "Foto guardada con éxito.Ya puedes compartirlas en red de contacto",
      "Eliminar la dirección ?",
      "Eliminar ?",
      "Eliminar todas huellas ?",
      "Cerrar sesión ?",
      "Anular la orden ?",
      "Eliminar la orden ?",
      "Confirmar la entrega ?",
      "Confirmar ",
      "Cancelar"
    ]
  },
  "es": {
    "transMsg": [
      "Descarga sin éxito",
      "Comentario subido",
      "Enviando...",
      "Descargando...",
      "Conseguido",
      "Guardado",
      "Agregado",
      "Solicitud enviada",
      "没有更多售后了",
      "No hay más favoritos",
      "Eliminado",
      "Gracias por tu opinión",
      "No hay más huellas",
      "Viculación fallada: inicia sesión",
      "Número celular vinculado",
      "No hay más orden",
      "Orden anulada",
      "Orden eliminada",
      "Recepción confirmada",
      "Inicio de sesión fallado con cuenta",
      "Inicio de sesión fallado con WeChat",
      "Elige dirección de entrega",
      "Maxímo 5 fotos",
      "Por favor escribe tu opinión ",
      "Por favor elige especificaciones completas",
      "Sin stock",
      "Transacción fallida",
      "Por favor ingresa tu nombre",
      "Por favor ingresa numero celular",
      "Por favor ingresa región, ciudad y comuna",
      "Por favor ingresa dirección completa",
      "Numero celular incorrecto",
      "Por favor elige tipo de reembolso",
      "Por favor ingresa razón de reembolso",
      "Por favor ingresa número de código",
      "Por favor elige tipo de comentario",
      "Por favor ingresa comentario",
      "Por favor ingresa número celular",
      "Aviso de actualización",
      "Información incorrecta",
      "Enviado",
      "Error al restablecer contraseña",
      "Error ",
      "Advertencia",
      "Foto guardada",
      "La nueva versión está lista.Querías reinicar la aplicación ?",
      "Por favor ingresa nombre usuario y contraseña",
      "Espacio de número celular es obligatorio",
      "Número celular incorrecto",
      "Código de verificación enviado",
      "Mínimo 6 números o letras para nombre usuario y contraseña",
      "Contraseñas diferente",
      "Espacio de número celular y código de verificación es obligatorio",
      "Número celular incorrecto",
      "Registración fallida",
      "Código de verificación enviado",
      "Mínimo 3 números o letras para nombre usuario y contraseña",
      "Carga sin éxito",
      "No se puede guardar sin autorización",
      "Foto guardada con éxito.Ya puedes compartirlas en red de contacto",
      "Eliminar la dirección ?",
      "Eliminar ?",
      "Eliminar todas huellas ?",
      "Cerrar sesión ?",
      "Anular la orden ?",
      "Eliminar la orden ?",
      "Confirmar la entrega ?",
      "Confirmar ",
      "Cancelar"
    ]
  }
}